Django/1.Intro Django/premier_projet/premier_projet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('salutation/', include('salutation.urls', namespace='salutation')),
    path('user/', include('utilisateur.urls', namespace='user')),
]

Django/1.Intro Django/premier_projet/salutation/urls.py
from django.urls import path
from . import views

app_name="salutation"

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('bonjour/', views.bonjour, name='bonjour'),
    path('au_revoir/', views.au_revoir, name='au_revoir'),
    path('formulaire/', views.FormulaireView.as_view(), name='formulaire'),
]

Django/1.Intro Django/premier_projet/utilisateur/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name="user"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='utilisateur/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

Django/1.Intro Django/premier_projet/salutation/models.py
from django.db import models
from django.contrib import admin

class Article(models.Model):
    titre = models.CharField(max_length=100)
    auteur =  models.CharField(max_length=100)
    contenu = models.TextField()

    def __str__(self):
        return self.titre
    
class ArticleAdmin(admin.ModelAdmin):
    list_display = ("titre", "auteur", "contenu")
    list_filter = ("auteur",)

Django/1.Intro Django/premier_projet/utilisateur/models.py
from django.db import models

# Create your models here.

Django/1.Intro Django/premier_projet/salutation/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['titre', 'auteur', 'contenu']

Django/1.Intro Django/premier_projet/salutation/views.py
from django.urls import reverse
from django.shortcuts import render, redirect, HttpResponse
from django.views.generic import TemplateView, FormView
from .forms import ArticleForm

# def salutation_home(request):
#     contexte ={
#         "user": "pierpoljak"
#     }
#     return render(request, "salutation/home.html", contexte)

class HomeView(TemplateView):
    template_name = "salutation/home.html"

    def get_context_data(self, **kwargs):
        contexte = super().get_context_data(**kwargs)
        contexte["user"] = "pierpoljak"
        return contexte
    
def bonjour(request):
    return render(request, "salutation/bonjour.html")

def au_revoir(request):
    return render(request, "salutation/au_revoir.html")

# def ajouter_article(request):
#     if request.method ==  "POST":
#         form = ArticleForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('salutation:home') # redirect(reverse('salutation:home'))

#     else:
#         form = ArticleForm()
#         return render(request, "salutation/formulaire.html", {"form": form})

class FormulaireView(FormView):
    template_name = "salutation/formulaire.html"
    form_class = ArticleForm
    # success_url = '/salutation/home'

    def form_valid(self, form):
        form.save()
        return redirect(reverse('salutation:home'))

Django/1.Intro Django/premier_projet/utilisateur/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def dashboard(request):
    return render(request, 'utilisateur/dashboard.html')

Django/1.Intro Django/premier_projet/salutation/templates/salutation/au_revoir.html
{% extends "salutation/base.html" %}
{% block title %}Homepage de Salutation{% endblock %}
{% block content %}
<h2>Au revoir tout le monde !</h2>
{% endblock %}

Django/1.Intro Django/premier_projet/salutation/templates/salutation/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock%}</title>
</head>
<body>
    <h1>Mon premier site Django</h1>
    {% block content %}{% endblock%}
    <footer><p>Pied de page</p></footer>
</body>
</html>

Django/1.Intro Django/premier_projet/salutation/templates/salutation/bonjour.html
{% extends "salutation/base.html" %}
{% block title %}Homepage de Salutation{% endblock %}
{% block content %}
<h2>Bonjour tout le monde !</h2>
{% endblock %}

Django/1.Intro Django/premier_projet/salutation/templates/salutation/formulaire.html
{% extends "salutation/base.html" %}
{% block title %}Homepage de Salutation{% endblock %}
{% block content %}
<h2>Mon premier ModelForm !</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Ajouter article</button>
</form>
{% endblock %}

Django/1.Intro Django/premier_projet/salutation/templates/salutation/home.html
{% extends "salutation/base.html" %}
{% block title %}Homepage de Salutation{% endblock %}
{% block content %}
<h2>Home de mon application Salutation !</h2>
<p>pour saluer {{ user }}</p>
<a href="{% url 'salutation:bonjour' %}">Lien vers bonjour</a>
<a href="{% url 'salutation:au_revoir' %}">Lien vers au revoir</a>

{% endblock %}

Django/1.Intro Django/premier_projet/utilisateur/templates/utilisateur/dashboard.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
</head>
<body>
    <h2>Page du dashboard utilisateur</h2>
    <p>Utilisateur :  {{ user.username }} </p>
    <form method="post" action="{% url 'user:logout' %}">
        {% csrf_token %}
        <button type="submit">Se déconnecter</button>
    </form>
</body>
</html>

Django/1.Intro Django/premier_projet/utilisateur/templates/utilisateur/login.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page de connexion</title>
</head>
<body>
    <h2>Connexion</h2>
    <p>{{ user.}}</p>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Se connecter</button>
    </form>
</body>
</html>